#!/bin/bash
#ddev-generated

if [[ ! -d "test/playwright" ]]; then
  mkdir -p test/playwright
fi

# Providing --yes and --quiet flags in order to install without prompts.
ddev exec -d /var/www/html/test/playwright npx --yes create-playwright@latest --quiet --install-deps
#cp -R .ddev/playwright/tests test/playwright
ln -s .ddev/playwright/tests test/playwright/tests
#cp .ddev/playwright/playwright.config.ts test/playwright
ln -s .ddev/playwright/playwright.config.ts test/playwright/playwright.config.ts

# ddev errors out on subsequent builds if we symlink these files. Instead, we
# copy them each time.
echo "Rebuilding web service with playwright dependencies..."
cp .ddev/web-build/disabled.Dockerfile.playwright .ddev/web-build/Dockerfile.playwright
ddev restart
