#!/usr/bin/env bash
#ddev-generated
## Description: Shortcut command to run playwright in the ui
## Usage: playwright-ui

set -e

ddev playwright test --ui-host 0.0.0.0 --ui-port 9323
## Afterwards, navigate to `<hostURI>:9324` to run tests with the UI.
## Setting the port here in reference to the container_port value from the config
## https://github.com/discoverygarden/ddev-dgi-playwright/blob/main/config.playwright.yml#L28
