#!/usr/bin/env bash
## Description: Shortcut command to run playwright in the ui
## Usage: playwright-ui

set -e

ddev playwright test --ui-host 0.0.0.0 --ui-port 9323
## Afterwards, navigate to `<hostURI>:9324` to run tests with the UI.
